source "https://supermarket.chef.io"

metadata

cookbook "git"
cookbook "apt", git: "git://github.com/opscode-cookbooks/apt.git"
cookbook "nano"
cookbook "build-essential"
cookbook "zsh"
cookbook "nginx"
cookbook "nodejs"
cookbook "php"
cookbook "composer"
cookbook "phpunit"
cookbook "php-mcrypt"
cookbook "memcached-cookbook"
cookbook "mysql2_chef_gem"
