name             'quintal'
maintainer       'João Vagner'
maintainer_email 'joao.vagner@gmail.com'
license          'All rights reserved'
description      'Installs/Configures quintal de trocas'
long_description 'Installs/Configures quintal de trocas'
version          '0.1.0'
