name             'quintal'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures quintal de trocas'
long_description 'Installs/Configures quintal de trocas'
version          '0.1.0'

depends 'apt'
depends 'dotdeb'
depends 'php'
depends 'composer'
depends 'nodejs'
depends 'mysql'
depends 'database'
depends 'mysql2_chef_gem'